export const products = [
  {
    id: 1,
    name: "Apple iPhone 12 (64GB) - Blue",
    desc: "6.1-inch (15.5 cm diagonal) Super Retina XDR display Ceramic Shield, tougher than any smartphone glass A14 Bionic chip, the fastest chip ever in a smartphone Advanced dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Deep Fusion, Smart HDR 3, 4K Dolby Vision HDR recording",
    price: 54900.0,
    rating: 4.3,
    company_name: "Apple",
    category: "mobile",
    img: "https://m.media-amazon.com/images/I/71ZOtNdaZCL._SL1500_.jpg,https://m.media-amazon.com/images/I/81hB-X3SMtL._SL1500_.jpg,https://m.media-amazon.com/images/I/81UBryv7mOL._SL1500_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 2,
    name: "OnePlus 9 5G (Astral Black, 8GB RAM, 128GB Storage)",
    desc: "Rear Triple Camera Co-Developed by Hasselblad, 48 MP Main camera, 50 MP Ultra Wide Angle Camera with Free Form Lens, 2 MP Monochorme Lens. Also comes with a 16 MP Front Camera Qualcomm Snapdragon 888 Processor with Adreno 660 GPU 6.55 Inches Fluid AMOLED Display with 120Hz refresh rate OnePlus Oxygen OS based on Andriod 11 Comes with 4500 mAh Battery with 65W Wired Charging",
    price: 40599.0,
    category: "mobile",
    company_name: "OnePlus",
    img: "https://m.media-amazon.com/images/I/61urU8k2lFL._SL1500_.jpg,https://m.media-amazon.com/images/I/613F+3n1N8L._SL1500_.jpg,https://m.media-amazon.com/images/I/61sR8kUIoCL._SL1500_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 3,
    name: "Tecno Spark 8 Pro (Turquoise Cyan, 7GB Expandable RAM 64GB Storage)",
    desc: "48MP High Resolution AI camera , Super Night Mode ,Intelligent Focus , 8MP Front Cam with Dual Front Flash , No support for Africa's frequency bands 6.8 FHD+Dot-in display , 90.52% screen to body ratio , 500nits Max Brightness , 120Hz Touch Sampling Rate 33W Super Fast Charger for rapid charging , Type C5000mAh battery , Upto 63 days long standby time Helio G85 Blazing Fast Gaming Processor , 1GHz Mali G52 GPU for Gaming greatness",
    price: 9999.0,
    category: "mobile",
    company_name: "Tecno",
    img: "https://m.media-amazon.com/images/I/81Q+kokB8GL._SL1500_.jpg,https://m.media-amazon.com/images/I/91Ipon95puL._SL1500_.jpg,https://m.media-amazon.com/images/I/815gKYN4OlL._SL1500_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 4,
    name: "Samsung Galaxy M32 5G (Sky Blue, 6GB RAM, 128GB Storage)",
    desc: "MediaTek , Dimensity 720 Octa Core 2GHz Processor with the widest 12 band support for a True 5G experience 16.55 centimeters (6.5-inch) TFT - Infinity V-cut display, HD+ resolution, 720 X 1600 pixels protected by Gorilla Glass 5 Versatile Quad camera setup-48MP (F 1.8) main camera + 8MP (F2.2) Ultra wide camera+ 5MP (F2.4) depth camera + 2MP (2.4) Macro Camera, 13MP (F2.2) front camera Monster 5000 mAh Battery , Memory, Storage & SIM: Upto 10GB RAM Plus, 128GB internal memory expandable up to 1TB, SIM 1 + Hybrid (SIM or MicroSD) Latest Android v11.0, One UI 3.1 operating system, available right out of the box",
    price: 16999.0,
    company_name: "Samsung",
    category: "mobile",
    img: "https://m.media-amazon.com/images/I/71os5DRhuSL._SL1500_.jpg,https://m.media-amazon.com/images/I/61vMdEauatL._SL1200_.jpg,https://m.media-amazon.com/images/I/61PBONnD1SL._SL1431_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 5,
    name: "OPPO A15s (Fancy White, 4GB, 128GB Storage) AI Triple Camera",
    desc: "13MP main camera + 2MP Depth camera + 2MP Macro lens with 8MP Front 16.55 centimeters (6.52-inch) HD+ Display with 1520 x 720 Pixel Resolution-Rear Fingerprint Sensor + AI face unlock, Eye comfort - filters Blue light to reduce damage to the eyes. Battery: 4230 mAh Lithium-Polymer Battery providing talk-time of 29 hours and standby time of 323 hours. Memory & Storage: 4GB Ram with 128GB Storage , Dual Nano Sim with Dual standby (4G+4G)",
    price: 11990.0,
    category: "mobile",
    company_name: "Oppo",
    img: "https://m.media-amazon.com/images/I/71TdXNLT1FL._SL1500_.jpg,https://m.media-amazon.com/images/I/711LOjRlSxL._SL1500_.jpg,https://m.media-amazon.com/images/I/71D8Q0hqh3L._SL1500_.jpg",
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 6,
    name: "Lenovo IdeaPad 5 Pro AMD Ryzen 5800U 14 (35.56cm) QHD IPS Thin & Light Laptop(16GB/1TB SSD/AMD Radeon Graphics/3Yr Warranty/Windows 11/Office 2021/Backlit/300Nits/Storm Grey/1.41Kg), 82L700CYIN",
    desc: "Processor: 5th Gen AMD Ryzen 7 5800U , Speed: 1.9 GHz (Base) - 4.4 GHz (Max) , 8 Cores , 4MB L2 / 16MB L3 Cache OS: Pre-Loaded Windows 11 Home with Lifetime Validity Pre-Installed: MS Office Home and Student 2021 Memory and Storage: 16GB RAM DDR4-3200 , 1 TB SSD Graphics : Integrated AMD Radeon Graphics Display: 14 2.2K QHD Display (2240x1400) , Brightness: 300 nits , Refresh Rate : 60Hz , Anti-Glare , IPS Technology , 100% sRGB Design: 1.59 cm Thin and 1.38 kg Light , Aluminium Material Top , Backlit Keyboard",
    price: 80990.0,
    rating: 4.1,
    company_name: "Lenovo",
    category: "laptop",
    img: "https://m.media-amazon.com/images/I/71iczfK6yGL._SL1500_.jpg,https://m.media-amazon.com/images/I/611rj6-EFVL._SL1000_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 7,
    name: "ASUS TUF Gaming A15 (2021) 15.6-inch (39.62 cms) FHD 144Hz, AMD Ryzen 7 4800H, RTX 3050 4GB Graphics, Gaming Laptop (8GB/512GB SSD/Windows 10/Black/2.3 Kg), FA506IC-HN005T, Graphite Black",
    desc: "Free upgrade to Windows 11 when available. Disclaimer-Upgrade rollout plan is being finalized and is scheduled to begin late in 2021 and continue into 2022. Specific timing will vary by device. Processor: AMD Ryzen 7 4800H Processor, 2.9 GHz Base Speed, Up to 4.2 GHz Max Boost Speed, 8 Cores, 16 Threads, 8MB L3 Cache Access to over 100 high-quality PC games on Windows 10 One-month subscription to Xbox Game Pass that’s included with the purchase of your device Memory: 8GB SO-DIMM DDR4 3200MHz, Support Up to 32GB Using 2x SO-DIMM slots with , Storage: 512GB M.2 NVMe PCIe 3.0 SSD with additional empty 1x M.2 2280 PCIe 3.0 SSD Slot Graphics: Dedicated NVIDIA GeForce RTX 3050 GDDR6 4GB VRAM",
    price: 74990.0,
    rating: 4.3,
    company_name: "Asus",
    category: "laptop",
    img: "https://m.media-amazon.com/images/I/91zVSkGGZbS._SL1500_.jpg,https://m.media-amazon.com/images/I/71LJKvE+ciL._SL1500_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 8,
    name: "Lenovo Ideapad Gaming 3 AMD Ryzen 7 5800H 15.6 FHD IPS Gaming Laptop (16GB/512GB SSD/Windows 11/Nvidia GTX 1650 4GB/120Hz Refresh Rate/Backlit/3months Xbox Game Pass/Shadow Black/2.25Kg), 82K200X2IN",
    desc: "Processor: AMD Ryzen 7 5800H , Speed: 3.2 GHz (Base) - 4.4 GHz (Max) , 8 Cores , 16 Threads , 16MB Cache Display: 15.6 FHD (1920x1080) , IPS Technology , 120 Hz Refresh Rate , 250Nits Brightness , Anti-glare Graphics: NVIDIA GeForce GTX 1650 4GB GDDR6 Dedicated Graphics Memory and Storage: 16GB RAM DDR4-3200 , 512GB SSD Military Grade : MIL-STD-810G Qualified Design, Qualified for various Military Specification Tests like Low & High Temp (-25 to 63°C for 4 hrs), Temp Shock (-25 to 63°C one way temp Shock), Shock (122cm+ Drop Test), Vibration (4-32Hz over 2 hrs) Cooling: 100%imporved ventilation rate , 21% larger thermal Area , 35% higher TDP",
    price: 71990.0,
    rating: 4.1,
    company_name: "Lenovo",
    category: "laptop",
    img: "https://m.media-amazon.com/images/I/71--IQUHVwL._SL1500_.jpg,https://m.media-amazon.com/images/I/61ZINcrPYFL._SL1000_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 9,
    name: "Acer Nitro 5 AMD Ryzen 7 5800H/15.6 FHD IPS Display Gaming Laptop (16 GB/256 GB SSD/1TB HDD/Win 10 Home/6 GB Graphics/NVIDIA GeForce RTX 3060/144 Hz, Shale Black, 2.4 kg) Xbox Game Pass for PC",
    desc: "Dominating Performance : Conquer games and tasks alike, powered by an AMD Ryzen 7 5800H Mobile Processor, run your most demanding apps all at once with lightning-fast responsiveness. Experience hyper-efficient battery life thanks to industry-leading technology that keeps you productive and entertained from anywhere. The NVIDIA GeForce RTX 3060 laptop GPU is powered by the award-winning Ampere architecture—NVIDIA’s 2nd gen RTX—with new Ray Tracing Cores, Tensor Cores, & streaming multiprocessors for the most realistic ray-traced graphics & cutting-edge AI features. The ultimate performance for gamers & creators. Made for Speed : Explore games in greater detail with the sharp visuals of a 15.6” FHD 1920 x 1080 IPS display with 144Hz refresh rate, improved screen-to-body ratio to 80% with narrow bezels. Its hard-edged sleek lines evoke the gaming spirit of the Acer Nitro 5. The Nitro 5 looks and feels like it will help you take control.",
    price: 116799.0,
    rating: 4.6,
    company_name: "Acer",
    category: "laptop",
    img: "https://m.media-amazon.com/images/I/61eB8ZKNuwL._SL1024_.jpg,https://m.media-amazon.com/images/I/81M+CufUM0L._SL1500_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 10,
    name: "2021 Apple MacBook Pro (16-inch/41.05 cm, Apple M1 Pro chip with 10‑core CPU and 16‑core GPU, 16GB RAM, 512GB SSD) - Silver",
    desc: "Apple M1 Pro or M1 Max chip for a massive leap in CPU, GPU and machine learning performance Up to 10-core CPU delivers up to 2x faster performance to fly through pro workflows quicker than ever Up to 32-core GPU with up to 4x faster performance for graphics-intensive apps and games 16-core Neural Engine for up to 5x faster machine learning performance Longer battery life, up to 21 hours Up to 64GB of unified memory so everything you do is fast and fluid",
    price: 239900.0,
    rating: 4.7,
    company_name: "Apple",
    category: "laptop",
    img: "https://m.media-amazon.com/images/I/61Y30DpqRVL._SL1500_.jpg,https://m.media-amazon.com/images/I/81fM4olBVWL._SL1500_.jpg",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 11,
    name: "Noise ColorFit Qube SpO2 Smartwatch  (Black Strap, Regular)",
    desc: "Black Strap Color, Touchscreen, Water Resistant, SpO2 Sensor, Accelerometer Sensor, 7 Days Battery Life, 150 min charge time, Lithium Polymer Battery, Bluetooth",
    price: 1999,
    rating: 4.1,
    company_name: "Noice",
    category: "smartwatch",
    img: "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/t/i/a/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4ar4hjbgb.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/5/y/1/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4dyagh3uh.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/q/u/5/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y44dbzkqwg.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/k/y/y/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4sz5gdysf.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/o/s/o/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4e2jk9khc.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/u/c/p/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4hmsqhejv.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/f/d/a/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4fzyxcauw.jpeg?q=70",
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 12,
    name: 'boAt Storm 1.3" CurvedDisplay Smartwatch',
    desc: "3.3 cms(1.3 inches) Full Touch Screen Curved Display with Multiple Cloud Based Watch Faces (Note: Cloud Based Watch Faces will be Available via OTA Post Launch Wellness Mode: Spo2 (Real-time Blood Oxygen Level Monitor), 24x7 Heart Rate Monitor, Sleep monitor, Guided Breathing & Menstruation Tracker Metal Body Casing and 5ATM Water Resistance,Daily Activity Tracker and 9 sports Modes | Notifications with Vibration Alerts for Calls | Texts | Social media | Alarms and Sedentary Alerts,Fitness & Outdoor,Battery Runtime: Upto 10 days",
    price: 2499,
    rating: 4.1,
    company_name: "BoAt",
    category: "smartwatch",
    img: "https://rukminim1.flixcart.com/image/832/832/kzpw2vk0/smartwatch/k/x/i/-original-imagbnnrs7ngq8w6.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/kkprmvk0/smartwatch/v/j/n/storm-android-ios-boat-original-imafzzu29tguvtqg.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/kn22m4w0/smartwatch/f/h/8/storm-android-ios-boat-original-imagfthbarcen9fz.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/kk1h5e80/smartwatch/u/z/l/storm-android-ios-boat-original-imafzh2zr8jn3xzt.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/kgqvlow0/smartwatch/5/d/g/storm-android-ios-boat-original-imafwwzp45yte5zv.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/kgqvlow0/smartwatch/5/d/g/storm-android-ios-boat-original-imafwwzpqbjdsz3w.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/kgqvlow0/smartwatch/5/d/g/storm-android-ios-boat-original-imafwwzprvq2yqtf.jpeg?q=70,https://rukminim1.flixcart.com/image/832/832/khxqt8w0/smartwatch/k/3/h/android-ios-storm-boat-original-imafxu6zns6dmypj.jpeg?q=70",
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 13,
    name: "APPLE Watch Series 3 GPS - MTF02HN/A 38 mm Space Grey Aluminium Case with Black Sport Band  (Black Strap, Regular)",
    desc: "The Apple Watch Series 3 is a sleek accessory that's a must-have if you're all about staying fit. The watch features an enhanced Heart Rate app, and a built-in altimeter. Also carry and listen to your favourite songs on your wrist. Equipped with Siri, this smartwatch makes being active and staying connected enjoyable.",
    price: 20900,
    rating: 4.6,
    company_name: "Apple",
    category: "smartwatch",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/jmi22kw0/smartwatch/t/g/y/mtf02hn-a-apple-original-imaf9ec8nh6sscfh.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/ka2tmkw0/smartwatch/t/g/y/mtf02hn-a-ios-apple-original-imafrq4m5yvbhvz8.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/ka2tmkw0/smartwatch/t/g/y/mtf02hn-a-ios-apple-original-imafrq4ma6edzkmb.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 14,
    name: "FOSSIL Gen 5 Carlyle HR Smartwatch  (Black Strap, Free Size)",
    desc: "The Fossil Gen 5 smartwatch is a beautifully crafted wristwear that runs on Wear OS by Google. Compatible with both Android and iOS smartphones, this smartwatch easily syncs to your smartphone with the help of Bluetooth (V4.2) and Wi-Fi (802.11 b/g/n). With a battery that lasts all day long to keep up with all your activities, the Fossil Gen 5 also comes equipped with Google’s virtual assistant, the Google Assistant, that responds to all your queries via the built-in speakers of the watch. The smartwatch automatically monitors your heart rate as well as alerts you with a gentle buzz as and when you get notifications on your smartphone.",
    price: 18495,
    rating: 4,
    company_name: "FOSSIL",
    category: "smartwatch",
    img: "https://rukminim2.flixcart.com/image/416/416/k0mqtu80/smartwatch/g/g/p/ftw4025-fossil-original-imafkduxrypsxyhb.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/l0sgyvk0/smartwatch/l/r/1/-original-imagcg3kdz3fggmr.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 15,
    name: "SAMSUNG Galaxy Watch4 LTE (4.4cm) Smartwatch  (Silver Strap, Free Size)",
    desc: "Sensor Bioelectrical Impedance Analysis Sensor, Geomagnetic Sensor, Optical Heart Rate Sensor, Electrical Heart Sensor, Accelerometer, Barometer, Gyro Sensor, Light Sensor Charge Time-108 Minutes Battery Life-Upto 40 Hours Rechargeable Battery-Yes Charger Type Wireless Charger Other Features Holistic Sleep Analysis, Body Composition Analysis, Workout Tracking, Rotating Bezel for Timeless Look",
    price: 31999,
    rating: 4.2,
    company_name: "SAMSUNG",
    category: "smartwatch",
    img: "https://rukminim2.flixcart.com/image/416/416/ksxjs7k0/smartwatch/f/p/x/android-sm-r875fzsainu-samsung-yes-original-imag6dthuswwsypz.jpeg?q=70,https://youtu.be/O3cIBeMYsYY,https://rukminim2.flixcart.com/image/416/416/ksxjs7k0/smartwatch/d/5/n/android-sm-r875fzsainu-samsung-yes-original-imag6dthkhqmaxgu.jpeg?q=70",
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 16,
    name: "MarQ By Flipkart Convertible 4-in-1 Cooling 1.5 Ton 3 Star Split Inverter AC - White  (153SIAA22NW, Copper Condenser)",
    desc: " 4 in 1 Convertible AC from MarQ by Flipkart can be converted to 4 different capacities 0.9,1.1,1.3 and 1.6 ton based on the number of people and ambient temperature conditions. It will make your days and nights cool and pleasant even when the outdoor temperature is as high as 55°C*.You save up to Rs 69,000* per year with the Inverter Compressor that comes with 10 year warranty. Switch to your desired mode- Dry/Sleep/Eco based on your needs.Thanks to its copper condenser, you can experience long-lasting cooling and efficient heat transfer. The Blue Fin technology makes sure that the AC stays protected from water droplets, acid deposits, and salt making it corrosion resistance. It gives a Stabilizer free Operation and noiseless operation <43dB* * Under Controlled Internal testing conditions",
    price: 29990,
    rating: 3.9,
    company_name: "MarQ By Flipkart ",
    category: "Air Conditioner",
    img: "https://rukminim2.flixcart.com/image/416/416/kzfvzww0/air-conditioner-new/7/b/y/-original-imagbfzztkyhxfxs.jpeg?q=70,https://youtu.be/2vFY0zg2WjM",
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 17,
    name: "realme TechLife 4-in-1 Convertible 1 Ton 4 Star Split Inverter , AC - White  (104SIAA22WR, Copper Condenser)",
    desc: "Beat the heat without breaking a sweat by getting home this wonderful machine that takes care of all your summer needs, in terms of cooling. This 4 in 1 Convertible AC is suited for every occasion and keeps everything and everyone around it cool. Moreover, this AC consumes minimal energy and delivers maximum performance, thus proving to be easy on your pockets. 100% copper tubes adapted in this AC helps deliver impeccable performance and high-class ventilation for a long time.",
    price: 28790,
    rating: 4,
    company_name: "Realme",
    category: "Air Conditioner",
    img: "https://rukminim2.flixcart.com/image/416/416/l1pc3gw0/air-conditioner-new/7/u/r/-original-imagd7zw3xxwqpt6.jpeg?q=70,https://youtu.be/xNHJPxFUeAI",
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 18,
    name: "Voltas 1.5 Ton 3 Star Window AC - White  (183 DZA (R32)/183 DZA, Copper Condenser)",
    desc: "1.5 Ton : suitable for room size up to 150 sq ft 3 Star BEE Rating 2019 : For energy savings upto 15% (compared to Non-Inverter 1 Star) Auto Restart: No need to manually reset the settings post power-cut Copper : Energy efficient, best in class cooling with easy maintenance. Sleep Mode: Auto-adjusts the temperature to ensure comfort during your sleep",
    price: 28999,
    rating: 4.3,
    company_name: "Voltas",
    category: "Air Conditioner",
    img: "https://rukminim1.flixcart.com/image/416/416/jy3anbk0/air-conditioner-new/z/b/y/183-dza-r32-1-5-window-fixed-speed-voltas-original-imafgbz9hpnkwhs4.jpeg?q=70,https://youtu.be/N44vTZQJLy8,https://rukminim1.flixcart.com/image/416/416/jy3anbk0/air-conditioner-new/z/b/y/183-dza-r32-1-5-window-fixed-speed-voltas-original-imafgeh6yp7c33vy.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 19,
    name: "LG 1.5 Ton 3 Star Split Dual Inverter Convertible 5-in-1 Cooling HD Filter with Anti-Virus Protection AC - White  (PS-Q18KNXE, Copper Condenser)",
    desc: "You can make your space cool and comfortable even during sultry summers with the LG Dual Inverter Split Air Conditioner. With its varied speed dual rotary compressor, this air conditioner ensures a wide rotational frequency, offering a high-speed cooling range and energy efficiency. This way, it ensures quick cooling, silent operation, and long-lasting durability. Moreover, by adjusting the cooling capacity as per your preferences, this five-in-one air conditioner can easily meet your cooling requirements.",
    price: 36990,
    rating: 4.1,
    company_name: "LG",
    category: "Air Conditioner",
    img: "https://rukminim2.flixcart.com/image/416/416/kzpw2vk0/air-conditioner-new/q/n/t/-original-imagbz2fbs4zutty.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/kzpw2vk0/air-conditioner-new/l/a/e/-original-imagbz2f8qcdzghm.jpeg?q=70,https://youtu.be/N6GZheuvZvI",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 20,
    name: "Panasonic 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect - White  (CS/CU-SU18XKYTA, Copper Condenser)",
    desc: " Your summers can now be cool and comfortable with the Panasonic Miraie Split Inverter Air Conditioner. It is compatible with the AI-enabled Miraie app, which allows you to control the temperature, track operational status, and change modes. Featuring a personalised sleep mode, this air conditioner enables you to preset temperature profiles throughout the night for improved flexibility and comfort. And, you can also create different temperature profiles for weekdays and weekends. Furthermore, thanks to its auto-diagnosis feature, this AC can detect issues in advance and keep you notified.",
    price: 37490,
    rating: 4.3,
    company_name: "Panasonic",
    category: "Air Conditioner",
    img: "https://rukminim2.flixcart.com/image/416/416/l0r1j0w0/air-conditioner-new/n/i/w/-original-imagcgg5ktjp2p3j.jpeg?q=70,https://youtu.be/LKg7ZYRKmpc,https://rukminim2.flixcart.com/image/416/416/l0sgyvk0/air-conditioner-new/f/s/h/-original-imagcg9daxhwfutk.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 21,
    name: "Godrej 185 L Direct Cool Single Door 2 Star Refrigerator  (Wine Red, RD EDGE 200B 23 WRF WN RD)",
    desc: "You can keep your fruits, veggies, and dairy products fresh with the Godrej 185 L Direct Cool Single-door Refrigerator. Thanks to its insulation under the chiller tray, this refrigerator prevents water droplets from forming. With its large aqua space of up to 2.25 L capacity, this refrigerator enables you to conveniently store large water bottles and beverages. Moreover, even with starting voltage as low as 140 V, this refrigerator can perform effectively.",
    price: 12290,
    rating: 4.2,
    company_name: "Godrej",
    category: "Refrigerator",
    img: "https://rukminim2.flixcart.com/image/416/416/l2dmky80/refrigerator-new/j/8/u/-original-imagdqk5r23nghhf.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/l2dmky80/refrigerator-new/d/k/8/-original-imagdqk5hmtzcxef.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/l2dmky80/refrigerator-new/a/q/l/-original-imagdqk5gajnwkjy.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 22,
    name: "SAMSUNG 192 L Direct Cool Single Door 3 Star Refrigerator  (Saffron Red, RR20A1Y2YR8/HL)",
    desc: "The Samsung 192 L Direct Cool Single Door Refrigerator sports an artistic design to seamlessly blend in with your modern kitchen decor. The intelligent Digital Inverter Compressor adapts to your cooling requirements and delivers energy-efficient performance in near-silence. Thanks to the spacious Vege Box, you can store all your fresh greens together for convenient access. Furthermore, frequent power cuts won’t jeopardise the quality of your food, since this Smart Connect Inverter refrigerator can operate just as effectively on your household inverter.",
    price: 15090,
    rating: 4.3,
    company_name: "SAMSUNG",
    category: "Refrigerator",
    img: "https://rukminim2.flixcart.com/image/416/416/kl5hh8w0/refrigerator-new/q/u/o/rr20a1y2yr8-hl-3-2021-samsung-original-imagycyz93fmvgbg.jpeg?q=70,https://youtu.be/N3Y3gVd5Px8",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 23,
    name: "Voltas 195 L Direct Cool Single Door 3 Star Refrigerator  (VIVI WINE, RDC215CVWEX/2021)",
    desc: "Voltas 195 L Direct Cool Single Door 3 Star Refrigerator  (VIVI WINE, RDC215CVWEX/2021)",
    price: 15578,
    rating: 4.6,
    company_name: "Voltas",
    category: "Refrigerator",
    img: "https://rukminim2.flixcart.com/image/416/416/km2clu80/refrigerator-new/i/x/z/rdc215cvwex-3-2020-voltas-original-imagffyhfwdb8z8d.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/km2clu80/refrigerator-new/u/n/t/rdc215cvwex-3-2020-voltas-original-imagffyhgvhkfkas.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 24,
    name: "Whirlpool 215 L Direct Cool Single Door 5 Star Refrigerator  (Sapphire Mulia, 230 IMPRO PRM 5S INV SAPPHIRE MULIA)",
    desc: "If you are looking for a designer and energy-efficient refrigerator then this Whirlpool single-door fridge is ideal for you. Its inverter compressor comes equipped with the IntelliSense Inverter technology, which extends its life and optimizes its function. Moreover, the Honeycomb design of the vegetable keeps your vegetables fresh for longer. On top of that, it can automatically connect with your home inverter during a power cut to keep your food fresh and well-preserved.",
    price: 19990,
    rating: 3,
    company_name: "Whirlpool",
    category: "Refrigerator",
    img: "https://rukminim2.flixcart.com/image/416/416/kf2v3ww0/refrigerator-new/m/3/5/230-impro-roy-5s-inv-sapphire-flume-5-whirlpool-original-imafvm57vmddhzmz.jpeg?q=70,https://youtu.be/mQK15kekIT8",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 25,
    name: "Haier 346 L Frost Free Double Door 3 Star Convertible Refrigerator  (Brushline Silver, HEB-35TDS)",
    desc: "Store plenty of food items and keep them fresh for a long time in the Haier 346 L Magic Convertible Inverter Bottom-mounted Refrigerator. Its convertible freezer can effectively meet a myriad of freezing requirements. It has a Super Freezer Turbo Icing Mode that can quickly cool to -24°C. You can even serve ice cream and chocolates at a temperature of -14°C, thanks to its Energy Saving Mode. The 0°C setting is good for keeping beverage bottles, while the 2°C setting is ideal for dairy items such as milk and curd. Furthermore, at 5°C, this freezer is ideal for preserving fruits and vegetables.",
    price: 35790,
    rating: 4.9,
    company_name: "Haier",
    category: "Refrigerator",
    img: "https://rukminim2.flixcart.com/image/416/416/knoxnrk0/refrigerator-new/w/5/r/heb-35tds-3-2021-haier-original-imag2be6xmrdbdjt.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/knoxnrk0/refrigerator-new/u/n/w/heb-35tds-3-2021-haier-original-imag2be6mq6pwxej.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 26,
    name: "SAMSUNG 6.5 kg Diamond Drum feature Fully Automatic Top Load Silver  (WA65A4002VS/TL)",
    desc: "Are you looking for a washing machine that does not damage your clothes? If yes, bring home the Samsung washing machine that features centre jet technology that generates streams of water from the centre of the pulsator to prevent the clothes from settling on the pulsators and getting damaged. The diamond drum of this washing machine is gentle on clothes and even ensures delicate clothes are not damaged. The child lock function prevents the tampering of settings that virtues in before a wash program was initiated.",
    price: 14590,
    rating: 4,
    company_name: "SAMSUNG",
    category: "Washing Machine",
    img: "https://rukminim2.flixcart.com/image/416/416/kevpwnk0/washing-machine-new/g/t/5/wa65a4002vs-tl-samsung-original-imafvgz4qzfazbsh.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/kzllrbk0/washing-machine-new/l/c/0/-original-imagbkqpkqedg8nn.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/kzllrbk0/washing-machine-new/l/d/u/-original-imagbkqp5tmkcvkv.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 27,
    name: "Whirlpool 6 kg 5 Star,Turbo Scrub Technology Semi Automatic Top Load Grey  (Superb Atom 60i GREY DAZZLE)",
    desc: "Bring home the Whirlpool washing machine to get your laundry done with optimum convenience. This washing machine comes with an impeller so that stains on the clothes gets removed efficiently. The powerful motor of this appliance helps to rinse your clothes in all direction, thus ensuring spotlessly cleaned clothes. ",
    price: 9490,
    rating: 3,
    company_name: "Whirlpool",
    category: "Washing Machine",
    img: "https://rukminim2.flixcart.com/image/416/416/k9re3rk0/washing-machine-new/c/e/z/superb-atom-60i-grey-dazzle-whirlpool-original-imafrhfvghq32zyg.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/kae95e80/refrigerator-new/h/f/r/195-genius-roy-4s-3-whirlpool-original-imafrz3sbz55zhhs.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/ky90scw0/washing-machine-new/e/2/a/-original-imagajfhwasvs7wd.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 28,
    name: "Panasonic 7 kg 5 Star AquaBeat Wash Fully Automatic Top Load Grey  (NA-F70LF1HRB)",
    desc: "If you are looking for a fully-automatic washing machine, you should consider this Panasonic washer dryer. It comes with a rust-proof body that makes it durable and long-lasting. Thanks to its Aqua Beat feature, even your dirtiest of clothes come out clean and fresh after a wash. Its customizable washing programs let you choose a washing course that best suits the fabric being put for a wash. To top it off, the washing machine also features a Magic Filter that, irrespective of the water level in the machine, traps dirt and lint from clothes while they are being washed.",
    price: 16790,
    rating: 3.5,
    company_name: "Panasonic",
    category: "Washing Machine",
    img: "https://rukminim2.flixcart.com/image/416/416/kjrh2fk0/washing-machine-new/n/g/h/7-na-f70lf1hrb-panasonic-original-imafz965ahvchzxz.jpeg?q=70,https://youtu.be/x0aM41rMneY,https://rukminim2.flixcart.com/image/416/416/kjrh2fk0/washing-machine-new/n/g/h/7-na-f70lf1hrb-panasonic-original-imafz96522hfeaxd.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 29,
    name: "Motorola 10.5 kg 5 Star Smart Wi-Fi Enabled Inverter Technology Fully Automatic Front Load with In-built Heater Grey  (105FLIWBM5DG)",
    desc: "Doing your laundry can be hectic. Boasting TruWifi Technology, this washing machine can be controlled from anywhere using your smartphone. Its TruSmart Sensors and Renesas Chipset ensure that the temperature, water level, foam level, weight, and speed are ideal to give your clothes a nice wash even when the voltage is fluctuating (up to 500 V).",
    price: 28990,
    rating: 3.5,
    company_name: "Motorola",
    category: "Washing Machine",
    img: "https://rukminim1.flixcart.com/image/416/416/kgl5ua80/washing-machine-new/k/w/s/105fliwbm5dg-motorola-original-imafwse6knmbgy48.jpeg?q=70,https://rukminim1.flixcart.com/image/416/416/kfzq8i80/washing-machine-new/k/w/s/105fliwbm5dg-motorola-original-imafwb6vxmhzy5hw.jpeg?q=70,https://youtu.be/VGWYR9H33Eo",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 30,
    name: "BOSCH 7 kg Drive Motor, Anti Tangle, Anti Vibration Fully Automatic Front Load with In-built Heater Grey  (WAJ2416SIN)",
    desc: "Fully Automatic Front Load Washing Machines have Great Wash Quality with very less running cost 1200 RPM : Higher the spin speed, lower the drying time 5 Star Rating 7 kg",
    price: 31990,
    rating: 4.6,
    company_name: "BOSCH",
    category: "Washing Machine",
    img: "https://rukminim2.flixcart.com/image/416/416/kkzrpu80/washing-machine-new/8/i/a/7-waj2416sin-bosch-original-imagy7rpzjhvvhdv.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/kwnv6a80/washing-machine-new/7/4/z/-original-imag9abgbusewazp.jpeg?q=70,https://youtu.be/boE98Fq1We4",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 30,
    name: "BOSCH 7 kg Drive Motor, Anti Tangle, Anti Vibration Fully Automatic Front Load with In-built Heater Grey  (WAJ2416SIN)",
    desc: "Fully Automatic Front Load Washing Machines have Great Wash Quality with very less running cost 1200 RPM : Higher the spin speed, lower the drying time 5 Star Rating 7 kg",
    price: 31990,
    rating: 4.6,
    company_name: "BOSCH",
    category: "Washing Machine",
    img: "https://rukminim2.flixcart.com/image/416/416/kkzrpu80/washing-machine-new/8/i/a/7-waj2416sin-bosch-original-imagy7rpzjhvvhdv.jpeg?q=70,https://rukminim2.flixcart.com/image/416/416/kwnv6a80/washing-machine-new/7/4/z/-original-imag9abgbusewazp.jpeg?q=70,https://youtu.be/boE98Fq1We4",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 31,
    name: "LG 80 cm (32 inch) HD Ready LED Smart TV  (32LM565BPTA)",
    desc: "This LG Smart TV comes equipped with a host of impressive features to delight your senses. While its Dynamic Color Enhancer produces vivid and lifelike colors on the screen, the LG WebOS feature lets you watch shows and movies from your favourite streaming services, such as Netflix and Disney+Hotstar. Also, the DTX Virtual:X technology delivers multi-dimensional sound to ensure an immersive listening experience.",
    price: 17499,
    rating: 3,
    company_name: "LG",
    category: "TV",
    img: "https://rukminim2.flixcart.com/image/832/832/kdyus280/television/g/d/q/lg-32lm565bpta-32lm565bpta-original-imafurgkdrjfggbw.jpeg?q=70,https://rukminim2.flixcart.com/image/832/832/kdyus280/television/g/d/q/lg-32lm565bpta-32lm565bpta-original-imafurgkf3ycgxbw.jpeg?q=70,https://rukminim2.flixcart.com/image/832/832/kdyus280/television/g/d/q/lg-32lm565bpta-32lm565bpta-original-imafurgk3fsqyjwm.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 32,
    name: "Vu Premium 108 cm (43 inch) Full HD LED Smart Android TV  (43UA)",
    desc: "Stay entertained and engrossed in your favourite content as you bring home this Vu Premium 43UA Television. The High Bright IPS panel of this TV helps to optimize brightness and enhance the visual quality thus, transforming your TV-viewing experience into an immersive one. Also, this TV comes with 30 W speakers and Dolby Audio so that you can indulge in excellent sound experience. Moreover, thanks to the in-built access to Netflix, Amazon, and Hotstar streaming platforms, you can enjoy accessing multiple content according to your convenience.",
    price: 21999,
    rating: 4.2,
    company_name: "Vu",
    category: "TV",
    img: "https://rukminim2.flixcart.com/image/832/832/kynb6vk0/television/r/5/g/-original-imagatzzmayhsjzc.jpeg?q=70,https://rukminim2.flixcart.com/image/832/832/kxuqdu80/television/t/t/2/43ua-43ua-vu-original-imaga7snutyujtns.jpeg?q=70,https://rukminim2.flixcart.com/image/832/832/kxuqdu80/television/f/w/x/43ua-43ua-vu-original-imaga7snjzefh6cc.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 33,
    name: "Mi 5X 108 cm (43 inch) Ultra HD (4K) LED Smart Android TV with Dolby Atmos and Dolby Vision",
    desc: "The sleek and powerful Mi TV 5X is an ideal home entertainment option for your classy, modern humble abode. This appliance features a Premium Metal Bezel-less Design for a distraction-free visual experience, 30 W Powerful Speakers with Dolby Atmos for immersive sound, and Far-field Mics with Google Assistant to easily manage your entertainment using your voice.",
    price: 31999,
    rating: 4.5,
    company_name: "Mi",
    category: "TV",
    img: "https://rukminim2.flixcart.com/image/832/832/ksoz53k0/television/c/p/h/l43m6-es-mi-original-imag6774wykv4ps8.jpeg?q=70,https://youtu.be/LMSgBcgP13I",

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 34,
    name: "OnePlus U1S 139 cm (55 inch) Ultra HD (4K) LED Smart Android TV  (55UC1A00)",
    desc: " The OnePlus 50UC1A00 TV is your one home entertainment appliance for immersive, unlimited, and exciting audio-visual delight. This television features a 4K UHD Display for detailed, clear, and immersive visuals, Dynaudio sound offers well-balanced audio, and OnePlus Connect 2.0 to connect your smartphone to this TV.",
    price: 46999,
    rating: 4.9,
    company_name: "OnePlus",
    category: "TV",
    img: "https://rukminim2.flixcart.com/image/832/832/kuwzssw0/television/d/f/q/u-series-55-u1s-55uc1a00-oneplus-original-imag7xtn86zveeb7.jpeg?q=70,https://youtu.be/7MAEulKAAUU",

    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 35,
    name: "Xiaomi 5A 100 cm (40 inch) Full HD LED Smart Android TV with Dolby Audio (2022 Model)",
    desc: "You can enjoy your favourite movies, catch up on news, and binge-watch TV series on the Xiaomi L40M7-EAIN FHD Smart TV. It features an elegant metal frame with a bezel-less design, allowing you to enjoy a widescreen view. In addition, this TV is sure to enhance your aural experience with Dolby Audio, which provides 24 W high-fidelity sound. Furthermore, boasting a full HD display and wide colour gamut, this TV provides high-quality visuals.",
    price: 22999,
    rating: 4.3,
    company_name: "Xiaomi",
    category: "TV",
    img: "https://rukminim2.flixcart.com/image/832/832/l2ghgnk0/television/k/t/h/l40m7-eain-mi-original-imagdsdwkephupc5.jpeg?q=70,https://rukminim2.flixcart.com/image/832/832/l2ghgnk0/television/i/q/g/l40m7-eain-mi-original-imagdsdwgbrtzyzz.jpeg?q=70",

    date: "23-03-2022",
    delivery: true,
  },
];

export const ecproducts = [
  {
    id: 1,
    name: "Apple iPhone 12 (64GB) - Blue",
    desc: "6.1-inch (15.5 cm diagonal) Super Retina XDR display Ceramic Shield, tougher than any smartphone glass A14 Bionic chip, the fastest chip ever in a smartphone Advanced dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Deep Fusion, Smart HDR 3, 4K Dolby Vision HDR recording",
    price: 54900.0,
    rating: 4.3,
    company_name: "Apple",
    category: "mobile",
    img: [
      "https://m.media-amazon.com/images/I/71ZOtNdaZCL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81hB-X3SMtL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81UBryv7mOL._SL1500_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 2,
    name: "OnePlus 9 5G (Astral Black, 8GB RAM, 128GB Storage)",
    desc: "Rear Triple Camera Co-Developed by Hasselblad, 48 MP Main camera, 50 MP Ultra Wide Angle Camera with Free Form Lens, 2 MP Monochorme Lens. Also comes with a 16 MP Front Camera Qualcomm Snapdragon 888 Processor with Adreno 660 GPU 6.55 Inches Fluid AMOLED Display with 120Hz refresh rate OnePlus Oxygen OS based on Andriod 11 Comes with 4500 mAh Battery with 65W Wired Charging",
    price: 40599.0,
    category: "mobile",
    company_name: "OnePlus",
    img: [
      "https://m.media-amazon.com/images/I/61urU8k2lFL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/613F+3n1N8L._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61sR8kUIoCL._SL1500_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 3,
    name: "Tecno Spark 8 Pro (Turquoise Cyan, 7GB Expandable RAM 64GB Storage)",
    desc: "48MP High Resolution AI camera , Super Night Mode ,Intelligent Focus , 8MP Front Cam with Dual Front Flash , No support for Africa's frequency bands 6.8 FHD+Dot-in display , 90.52% screen to body ratio , 500nits Max Brightness , 120Hz Touch Sampling Rate 33W Super Fast Charger for rapid charging , Type C5000mAh battery , Upto 63 days long standby time Helio G85 Blazing Fast Gaming Processor , 1GHz Mali G52 GPU for Gaming greatness",
    price: 9999.0,
    category: "mobile",
    company_name: "Tecno",
    img: [
      "https://m.media-amazon.com/images/I/81Q+kokB8GL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91Ipon95puL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/815gKYN4OlL._SL1500_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 4,
    name: "Samsung Galaxy M32 5G (Sky Blue, 6GB RAM, 128GB Storage)",
    desc: "MediaTek , Dimensity 720 Octa Core 2GHz Processor with the widest 12 band support for a True 5G experience 16.55 centimeters (6.5-inch) TFT - Infinity V-cut display, HD+ resolution, 720 X 1600 pixels protected by Gorilla Glass 5 Versatile Quad camera setup-48MP (F 1.8) main camera + 8MP (F2.2) Ultra wide camera+ 5MP (F2.4) depth camera + 2MP (2.4) Macro Camera, 13MP (F2.2) front camera Monster 5000 mAh Battery , Memory, Storage & SIM: Upto 10GB RAM Plus, 128GB internal memory expandable up to 1TB, SIM 1 + Hybrid (SIM or MicroSD) Latest Android v11.0, One UI 3.1 operating system, available right out of the box",
    price: 16999.0,
    company_name: "Samsung",
    category: "mobile",
    img: [
      "https://m.media-amazon.com/images/I/71os5DRhuSL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61vMdEauatL._SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61PBONnD1SL._SL1431_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 5,
    name: "OPPO A15s (Fancy White, 4GB, 128GB Storage) AI Triple Camera",
    desc: "13MP main camera + 2MP Depth camera + 2MP Macro lens with 8MP Front 16.55 centimeters (6.52-inch) HD+ Display with 1520 x 720 Pixel Resolution-Rear Fingerprint Sensor + AI face unlock, Eye comfort - filters Blue light to reduce damage to the eyes. Battery: 4230 mAh Lithium-Polymer Battery providing talk-time of 29 hours and standby time of 323 hours. Memory & Storage: 4GB Ram with 128GB Storage , Dual Nano Sim with Dual standby (4G+4G)",
    price: 11990.0,
    category: "mobile",
    company_name: "Oppo",
    img: [
      "https://m.media-amazon.com/images/I/71TdXNLT1FL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/711LOjRlSxL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71D8Q0hqh3L._SL1500_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 6,
    name: "Lenovo IdeaPad 5 Pro AMD Ryzen 5800U 14 (35.56cm) QHD IPS Thin & Light Laptop(16GB/1TB SSD/AMD Radeon Graphics/3Yr Warranty/Windows 11/Office 2021/Backlit/300Nits/Storm Grey/1.41Kg), 82L700CYIN",
    desc: "Processor: 5th Gen AMD Ryzen 7 5800U , Speed: 1.9 GHz (Base) - 4.4 GHz (Max) , 8 Cores , 4MB L2 / 16MB L3 Cache OS: Pre-Loaded Windows 11 Home with Lifetime Validity Pre-Installed: MS Office Home and Student 2021 Memory and Storage: 16GB RAM DDR4-3200 , 1 TB SSD Graphics : Integrated AMD Radeon Graphics Display: 14 2.2K QHD Display (2240x1400) , Brightness: 300 nits , Refresh Rate : 60Hz , Anti-Glare , IPS Technology , 100% sRGB Design: 1.59 cm Thin and 1.38 kg Light , Aluminium Material Top , Backlit Keyboard",
    price: 80990.0,
    rating: 4.1,
    company_name: "Lenovo",
    category: "laptop",
    img: [
      "https://m.media-amazon.com/images/I/71iczfK6yGL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/611rj6-EFVL._SL1000_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 7,
    name: "ASUS TUF Gaming A15 (2021) 15.6-inch (39.62 cms) FHD 144Hz, AMD Ryzen 7 4800H, RTX 3050 4GB Graphics, Gaming Laptop (8GB/512GB SSD/Windows 10/Black/2.3 Kg), FA506IC-HN005T, Graphite Black",
    desc: "Free upgrade to Windows 11 when available. Disclaimer-Upgrade rollout plan is being finalized and is scheduled to begin late in 2021 and continue into 2022. Specific timing will vary by device. Processor: AMD Ryzen 7 4800H Processor, 2.9 GHz Base Speed, Up to 4.2 GHz Max Boost Speed, 8 Cores, 16 Threads, 8MB L3 Cache Access to over 100 high-quality PC games on Windows 10 One-month subscription to Xbox Game Pass that’s included with the purchase of your device Memory: 8GB SO-DIMM DDR4 3200MHz, Support Up to 32GB Using 2x SO-DIMM slots with , Storage: 512GB M.2 NVMe PCIe 3.0 SSD with additional empty 1x M.2 2280 PCIe 3.0 SSD Slot Graphics: Dedicated NVIDIA GeForce RTX 3050 GDDR6 4GB VRAM",
    price: 74990.0,
    rating: 4.3,
    company_name: "Asus",
    category: "laptop",
    img: [
      "https://m.media-amazon.com/images/I/91zVSkGGZbS._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71LJKvE+ciL._SL1500_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 8,
    name: "Lenovo Ideapad Gaming 3 AMD Ryzen 7 5800H 15.6 FHD IPS Gaming Laptop (16GB/512GB SSD/Windows 11/Nvidia GTX 1650 4GB/120Hz Refresh Rate/Backlit/3months Xbox Game Pass/Shadow Black/2.25Kg), 82K200X2IN",
    desc: "Processor: AMD Ryzen 7 5800H , Speed: 3.2 GHz (Base) - 4.4 GHz (Max) , 8 Cores , 16 Threads , 16MB Cache Display: 15.6 FHD (1920x1080) , IPS Technology , 120 Hz Refresh Rate , 250Nits Brightness , Anti-glare Graphics: NVIDIA GeForce GTX 1650 4GB GDDR6 Dedicated Graphics Memory and Storage: 16GB RAM DDR4-3200 , 512GB SSD Military Grade : MIL-STD-810G Qualified Design, Qualified for various Military Specification Tests like Low & High Temp (-25 to 63°C for 4 hrs), Temp Shock (-25 to 63°C one way temp Shock), Shock (122cm+ Drop Test), Vibration (4-32Hz over 2 hrs) Cooling: 100%imporved ventilation rate , 21% larger thermal Area , 35% higher TDP",
    price: 71990.0,
    rating: 4.1,
    company_name: "Lenovo",
    category: "laptop",
    img: [
      "https://m.media-amazon.com/images/I/71--IQUHVwL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61ZINcrPYFL._SL1000_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 9,
    name: "Acer Nitro 5 AMD Ryzen 7 5800H/15.6 FHD IPS Display Gaming Laptop (16 GB/256 GB SSD/1TB HDD/Win 10 Home/6 GB Graphics/NVIDIA GeForce RTX 3060/144 Hz, Shale Black, 2.4 kg) Xbox Game Pass for PC",
    desc: "Dominating Performance : Conquer games and tasks alike, powered by an AMD Ryzen 7 5800H Mobile Processor, run your most demanding apps all at once with lightning-fast responsiveness. Experience hyper-efficient battery life thanks to industry-leading technology that keeps you productive and entertained from anywhere. The NVIDIA GeForce RTX 3060 laptop GPU is powered by the award-winning Ampere architecture—NVIDIA’s 2nd gen RTX—with new Ray Tracing Cores, Tensor Cores, & streaming multiprocessors for the most realistic ray-traced graphics & cutting-edge AI features. The ultimate performance for gamers & creators. Made for Speed : Explore games in greater detail with the sharp visuals of a 15.6” FHD 1920 x 1080 IPS display with 144Hz refresh rate, improved screen-to-body ratio to 80% with narrow bezels. Its hard-edged sleek lines evoke the gaming spirit of the Acer Nitro 5. The Nitro 5 looks and feels like it will help you take control.",
    price: 116799.0,
    rating: 4.6,
    company_name: "Acer",
    category: "laptop",
    img: [
      "https://m.media-amazon.com/images/I/61eB8ZKNuwL._SL1024_.jpg",
      "https://m.media-amazon.com/images/I/81M+CufUM0L._SL1500_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 10,
    name: "2021 Apple MacBook Pro (16-inch/41.05 cm, Apple M1 Pro chip with 10‑core CPU and 16‑core GPU, 16GB RAM, 512GB SSD) - Silver",
    desc: "Apple M1 Pro or M1 Max chip for a massive leap in CPU, GPU and machine learning performance Up to 10-core CPU delivers up to 2x faster performance to fly through pro workflows quicker than ever Up to 32-core GPU with up to 4x faster performance for graphics-intensive apps and games 16-core Neural Engine for up to 5x faster machine learning performance Longer battery life, up to 21 hours Up to 64GB of unified memory so everything you do is fast and fluid",
    price: 239900.0,
    rating: 4.7,
    company_name: "Apple",
    category: "laptop",
    img: [
      "https://m.media-amazon.com/images/I/61Y30DpqRVL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81fM4olBVWL._SL1500_.jpg",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 11,
    name: "Noise ColorFit Qube SpO2 Smartwatch  (Black Strap, Regular)",
    desc: "Black Strap Color, Touchscreen, Water Resistant, SpO2 Sensor, Accelerometer Sensor, 7 Days Battery Life, 150 min charge time, Lithium Polymer Battery, Bluetooth",
    price: 1999,
    rating: 4.1,
    company_name: "Noice",
    category: "smartwatch",
    img: [
      "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/t/i/a/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4ar4hjbgb.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/5/y/1/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4dyagh3uh.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/q/u/5/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y44dbzkqwg.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/k/y/y/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4sz5gdysf.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/o/s/o/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4e2jk9khc.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/u/c/p/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4hmsqhejv.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/ku1k4280/smartwatch/f/d/a/android-ios-wrb-sw-colorfitqubeoxy-std-blk-blk-noise-no-original-imag79y4fzyxcauw.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 12,
    name: 'boAt Storm 1.3" CurvedDisplay Smartwatch',
    desc: "3.3 cms(1.3 inches) Full Touch Screen Curved Display with Multiple Cloud Based Watch Faces (Note: Cloud Based Watch Faces will be Available via OTA Post Launch Wellness Mode: Spo2 (Real-time Blood Oxygen Level Monitor), 24x7 Heart Rate Monitor, Sleep monitor, Guided Breathing & Menstruation Tracker Metal Body Casing and 5ATM Water Resistance,Daily Activity Tracker and 9 sports Modes | Notifications with Vibration Alerts for Calls | Texts | Social media | Alarms and Sedentary Alerts,Fitness & Outdoor,Battery Runtime: Upto 10 days",
    price: 2499,
    rating: 4.1,
    company_name: "BoAt",
    category: "smartwatch",
    img: [
      "https://rukminim1.flixcart.com/image/832/832/kzpw2vk0/smartwatch/k/x/i/-original-imagbnnrs7ngq8w6.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/kkprmvk0/smartwatch/v/j/n/storm-android-ios-boat-original-imafzzu29tguvtqg.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/kn22m4w0/smartwatch/f/h/8/storm-android-ios-boat-original-imagfthbarcen9fz.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/kk1h5e80/smartwatch/u/z/l/storm-android-ios-boat-original-imafzh2zr8jn3xzt.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/kgqvlow0/smartwatch/5/d/g/storm-android-ios-boat-original-imafwwzp45yte5zv.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/kgqvlow0/smartwatch/5/d/g/storm-android-ios-boat-original-imafwwzpqbjdsz3w.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/kgqvlow0/smartwatch/5/d/g/storm-android-ios-boat-original-imafwwzprvq2yqtf.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/832/832/khxqt8w0/smartwatch/k/3/h/android-ios-storm-boat-original-imafxu6zns6dmypj.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 13,
    name: "APPLE Watch Series 3 GPS - MTF02HN/A 38 mm Space Grey Aluminium Case with Black Sport Band  (Black Strap, Regular)",
    desc: "The Apple Watch Series 3 is a sleek accessory that's a must-have if you're all about staying fit. The watch features an enhanced Heart Rate app, and a built-in altimeter. Also carry and listen to your favourite songs on your wrist. Equipped with Siri, this smartwatch makes being active and staying connected enjoyable.",
    price: 20900,
    rating: 4.6,
    company_name: "Apple",
    category: "smartwatch",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/jmi22kw0/smartwatch/t/g/y/mtf02hn-a-apple-original-imaf9ec8nh6sscfh.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/ka2tmkw0/smartwatch/t/g/y/mtf02hn-a-ios-apple-original-imafrq4m5yvbhvz8.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/ka2tmkw0/smartwatch/t/g/y/mtf02hn-a-ios-apple-original-imafrq4ma6edzkmb.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 14,
    name: "FOSSIL Gen 5 Carlyle HR Smartwatch  (Black Strap, Free Size)",
    desc: "The Fossil Gen 5 smartwatch is a beautifully crafted wristwear that runs on Wear OS by Google. Compatible with both Android and iOS smartphones, this smartwatch easily syncs to your smartphone with the help of Bluetooth (V4.2) and Wi-Fi (802.11 b/g/n). With a battery that lasts all day long to keep up with all your activities, the Fossil Gen 5 also comes equipped with Google’s virtual assistant, the Google Assistant, that responds to all your queries via the built-in speakers of the watch. The smartwatch automatically monitors your heart rate as well as alerts you with a gentle buzz as and when you get notifications on your smartphone.",
    price: 18495,
    rating: 4,
    company_name: "FOSSIL",
    category: "smartwatch",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/k0mqtu80/smartwatch/g/g/p/ftw4025-fossil-original-imafkduxrypsxyhb.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/l0sgyvk0/smartwatch/l/r/1/-original-imagcg3kdz3fggmr.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 15,
    name: "SAMSUNG Galaxy Watch4 LTE (4.4cm) Smartwatch  (Silver Strap, Free Size)",
    desc: "Sensor Bioelectrical Impedance Analysis Sensor, Geomagnetic Sensor, Optical Heart Rate Sensor, Electrical Heart Sensor, Accelerometer, Barometer, Gyro Sensor, Light Sensor Charge Time-108 Minutes Battery Life-Upto 40 Hours Rechargeable Battery-Yes Charger Type Wireless Charger Other Features Holistic Sleep Analysis, Body Composition Analysis, Workout Tracking, Rotating Bezel for Timeless Look",
    price: 31999,
    rating: 4.2,
    company_name: "SAMSUNG",
    category: "smartwatch",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/ksxjs7k0/smartwatch/f/p/x/android-sm-r875fzsainu-samsung-yes-original-imag6dthuswwsypz.jpeg?q=70",
      "https://youtu.be/O3cIBeMYsYY",
      "https://rukminim2.flixcart.com/image/416/416/ksxjs7k0/smartwatch/d/5/n/android-sm-r875fzsainu-samsung-yes-original-imag6dthkhqmaxgu.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 16,
    name: "MarQ By Flipkart Convertible 4-in-1 Cooling 1.5 Ton 3 Star Split Inverter AC - White  (153SIAA22NW, Copper Condenser)",
    desc: " 4 in 1 Convertible AC from MarQ by Flipkart can be converted to 4 different capacities 0.9,1.1,1.3 and 1.6 ton based on the number of people and ambient temperature conditions. It will make your days and nights cool and pleasant even when the outdoor temperature is as high as 55°C*.You save up to Rs 69,000* per year with the Inverter Compressor that comes with 10 year warranty. Switch to your desired mode- Dry/Sleep/Eco based on your needs.Thanks to its copper condenser, you can experience long-lasting cooling and efficient heat transfer. The Blue Fin technology makes sure that the AC stays protected from water droplets, acid deposits, and salt making it corrosion resistance. It gives a Stabilizer free Operation and noiseless operation <43dB* * Under Controlled Internal testing conditions",
    price: 29990,
    rating: 3.9,
    company_name: "MarQ By Flipkart ",
    category: " Air Conditioner",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/kzfvzww0/air-conditioner-new/7/b/y/-original-imagbfzztkyhxfxs.jpeg?q=70",
      "https://youtu.be/2vFY0zg2WjM",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 17,
    name: "realme TechLife 4-in-1 Convertible 1 Ton 4 Star Split Inverter , AC - White  (104SIAA22WR, Copper Condenser)",
    desc: "Beat the heat without breaking a sweat by getting home this wonderful machine that takes care of all your summer needs, in terms of cooling. This 4 in 1 Convertible AC is suited for every occasion and keeps everything and everyone around it cool. Moreover, this AC consumes minimal energy and delivers maximum performance, thus proving to be easy on your pockets. 100% copper tubes adapted in this AC helps deliver impeccable performance and high-class ventilation for a long time.",
    price: 28790,
    rating: 4,
    company_name: "Realme",
    category: " Air Conditioner",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/l1pc3gw0/air-conditioner-new/7/u/r/-original-imagd7zw3xxwqpt6.jpeg?q=70",
      "https://youtu.be/xNHJPxFUeAI",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 18,
    name: "Voltas 1.5 Ton 3 Star Window AC - White  (183 DZA (R32)/183 DZA, Copper Condenser)",
    desc: "1.5 Ton : suitable for room size up to 150 sq ft 3 Star BEE Rating 2019 : For energy savings upto 15% (compared to Non-Inverter 1 Star) Auto Restart: No need to manually reset the settings post power-cut Copper : Energy efficient, best in class cooling with easy maintenance. Sleep Mode: Auto-adjusts the temperature to ensure comfort during your sleep",
    price: 28999,
    rating: 4.3,
    company_name: "Voltas",
    category: " Air Conditioner",
    img: [
      "https://rukminim1.flixcart.com/image/416/416/jy3anbk0/air-conditioner-new/z/b/y/183-dza-r32-1-5-window-fixed-speed-voltas-original-imafgbz9hpnkwhs4.jpeg?q=70",
      "https://youtu.be/N44vTZQJLy8",
      "https://rukminim1.flixcart.com/image/416/416/jy3anbk0/air-conditioner-new/z/b/y/183-dza-r32-1-5-window-fixed-speed-voltas-original-imafgeh6yp7c33vy.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 19,
    name: "LG 1.5 Ton 3 Star Split Dual Inverter Convertible 5-in-1 Cooling HD Filter with Anti-Virus Protection AC - White  (PS-Q18KNXE, Copper Condenser)",
    desc: "You can make your space cool and comfortable even during sultry summers with the LG Dual Inverter Split Air Conditioner. With its varied speed dual rotary compressor, this air conditioner ensures a wide rotational frequency, offering a high-speed cooling range and energy efficiency. This way, it ensures quick cooling, silent operation, and long-lasting durability. Moreover, by adjusting the cooling capacity as per your preferences, this five-in-one air conditioner can easily meet your cooling requirements.",
    price: 36990,
    rating: 4.1,
    company_name: "LG",
    category: " Air Conditioner",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/kzpw2vk0/air-conditioner-new/q/n/t/-original-imagbz2fbs4zutty.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/kzpw2vk0/air-conditioner-new/l/a/e/-original-imagbz2f8qcdzghm.jpeg?q=70",
      "https://youtu.be/N6GZheuvZvI",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 20,
    name: "Panasonic 1.5 Ton 3 Star Split Inverter AC with Wi-fi Connect - White  (CS/CU-SU18XKYTA, Copper Condenser)",
    desc: " Your summers can now be cool and comfortable with the Panasonic Miraie Split Inverter Air Conditioner. It is compatible with the AI-enabled Miraie app, which allows you to control the temperature, track operational status, and change modes. Featuring a personalised sleep mode, this air conditioner enables you to preset temperature profiles throughout the night for improved flexibility and comfort. And, you can also create different temperature profiles for weekdays and weekends. Furthermore, thanks to its auto-diagnosis feature, this AC can detect issues in advance and keep you notified.",
    price: 37490,
    rating: 4.3,
    company_name: "Panasonic",
    category: " Air Conditioner",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/l0r1j0w0/air-conditioner-new/n/i/w/-original-imagcgg5ktjp2p3j.jpeg?q=70",
      "https://youtu.be/LKg7ZYRKmpc",
      "https://rukminim2.flixcart.com/image/416/416/l0sgyvk0/air-conditioner-new/f/s/h/-original-imagcg9daxhwfutk.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 21,
    name: "Godrej 185 L Direct Cool Single Door 2 Star Refrigerator  (Wine Red, RD EDGE 200B 23 WRF WN RD)",
    desc: "You can keep your fruits, veggies, and dairy products fresh with the Godrej 185 L Direct Cool Single-door Refrigerator. Thanks to its insulation under the chiller tray, this refrigerator prevents water droplets from forming. With its large aqua space of up to 2.25 L capacity, this refrigerator enables you to conveniently store large water bottles and beverages. Moreover, even with starting voltage as low as 140 V, this refrigerator can perform effectively.",
    price: 12290,
    rating: 4.2,
    company_name: "Godrej",
    category: "Refrigerator",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/l2dmky80/refrigerator-new/j/8/u/-original-imagdqk5r23nghhf.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/l2dmky80/refrigerator-new/d/k/8/-original-imagdqk5hmtzcxef.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/l2dmky80/refrigerator-new/a/q/l/-original-imagdqk5gajnwkjy.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 22,
    name: "SAMSUNG 192 L Direct Cool Single Door 3 Star Refrigerator  (Saffron Red, RR20A1Y2YR8/HL)",
    desc: "The Samsung 192 L Direct Cool Single Door Refrigerator sports an artistic design to seamlessly blend in with your modern kitchen decor. The intelligent Digital Inverter Compressor adapts to your cooling requirements and delivers energy-efficient performance in near-silence. Thanks to the spacious Vege Box, you can store all your fresh greens together for convenient access. Furthermore, frequent power cuts won’t jeopardise the quality of your food, since this Smart Connect Inverter refrigerator can operate just as effectively on your household inverter.",
    price: 15090,
    rating: 4.3,
    company_name: "SAMSUNG",
    category: "Refrigerator",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/kl5hh8w0/refrigerator-new/q/u/o/rr20a1y2yr8-hl-3-2021-samsung-original-imagycyz93fmvgbg.jpeg?q=70",
      "https://youtu.be/N3Y3gVd5Px8",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 23,
    name: "Voltas 195 L Direct Cool Single Door 3 Star Refrigerator  (VIVI WINE, RDC215CVWEX/2021)",
    desc: "Voltas 195 L Direct Cool Single Door 3 Star Refrigerator  (VIVI WINE, RDC215CVWEX/2021)",
    price: 15578,
    rating: 4.6,
    company_name: "Voltas",
    category: "Refrigerator",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/km2clu80/refrigerator-new/i/x/z/rdc215cvwex-3-2020-voltas-original-imagffyhfwdb8z8d.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/km2clu80/refrigerator-new/u/n/t/rdc215cvwex-3-2020-voltas-original-imagffyhgvhkfkas.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 24,
    name: "Whirlpool 215 L Direct Cool Single Door 5 Star Refrigerator  (Sapphire Mulia, 230 IMPRO PRM 5S INV SAPPHIRE MULIA)",
    desc: "If you are looking for a designer and energy-efficient refrigerator then this Whirlpool single-door fridge is ideal for you. Its inverter compressor comes equipped with the IntelliSense Inverter technology, which extends its life and optimizes its function. Moreover, the Honeycomb design of the vegetable keeps your vegetables fresh for longer. On top of that, it can automatically connect with your home inverter during a power cut to keep your food fresh and well-preserved.",
    price: 19990,
    rating: 3,
    company_name: "Whirlpool",
    category: "Refrigerator",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/kf2v3ww0/refrigerator-new/m/3/5/230-impro-roy-5s-inv-sapphire-flume-5-whirlpool-original-imafvm57vmddhzmz.jpeg?q=70",
      "https://youtu.be/mQK15kekIT8",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 25,
    name: "Haier 346 L Frost Free Double Door 3 Star Convertible Refrigerator  (Brushline Silver, HEB-35TDS)",
    desc: "Store plenty of food items and keep them fresh for a long time in the Haier 346 L Magic Convertible Inverter Bottom-mounted Refrigerator. Its convertible freezer can effectively meet a myriad of freezing requirements. It has a Super Freezer Turbo Icing Mode that can quickly cool to -24°C. You can even serve ice cream and chocolates at a temperature of -14°C, thanks to its Energy Saving Mode. The 0°C setting is good for keeping beverage bottles, while the 2°C setting is ideal for dairy items such as milk and curd. Furthermore, at 5°C, this freezer is ideal for preserving fruits and vegetables.",
    price: 35790,
    rating: 4.9,
    company_name: "Haier",
    category: "Refrigerator",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/knoxnrk0/refrigerator-new/w/5/r/heb-35tds-3-2021-haier-original-imag2be6xmrdbdjt.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/knoxnrk0/refrigerator-new/u/n/w/heb-35tds-3-2021-haier-original-imag2be6mq6pwxej.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 26,
    name: "SAMSUNG 6.5 kg Diamond Drum feature Fully Automatic Top Load Silver  (WA65A4002VS/TL)",
    desc: "Are you looking for a washing machine that does not damage your clothes? If yes, bring home the Samsung washing machine that features centre jet technology that generates streams of water from the centre of the pulsator to prevent the clothes from settling on the pulsators and getting damaged. The diamond drum of this washing machine is gentle on clothes and even ensures delicate clothes are not damaged. The child lock function prevents the tampering of settings that virtues in before a wash program was initiated.",
    price: 14590,
    rating: 4,
    company_name: "SAMSUNG",
    category: "Washing Machine",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/kevpwnk0/washing-machine-new/g/t/5/wa65a4002vs-tl-samsung-original-imafvgz4qzfazbsh.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/kzllrbk0/washing-machine-new/l/c/0/-original-imagbkqpkqedg8nn.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/kzllrbk0/washing-machine-new/l/d/u/-original-imagbkqp5tmkcvkv.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 27,
    name: "Whirlpool 6 kg 5 Star,Turbo Scrub Technology Semi Automatic Top Load Grey  (Superb Atom 60i GREY DAZZLE)",
    desc: "Bring home the Whirlpool washing machine to get your laundry done with optimum convenience. This washing machine comes with an impeller so that stains on the clothes gets removed efficiently. The powerful motor of this appliance helps to rinse your clothes in all direction, thus ensuring spotlessly cleaned clothes. ",
    price: 9490,
    rating: 3,
    company_name: "Whirlpool",
    category: "Washing Machine",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/k9re3rk0/washing-machine-new/c/e/z/superb-atom-60i-grey-dazzle-whirlpool-original-imafrhfvghq32zyg.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/kae95e80/refrigerator-new/h/f/r/195-genius-roy-4s-3-whirlpool-original-imafrz3sbz55zhhs.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/ky90scw0/washing-machine-new/e/2/a/-original-imagajfhwasvs7wd.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 28,
    name: "Panasonic 7 kg 5 Star AquaBeat Wash Fully Automatic Top Load Grey  (NA-F70LF1HRB)",
    desc: "If you are looking for a fully-automatic washing machine, you should consider this Panasonic washer dryer. It comes with a rust-proof body that makes it durable and long-lasting. Thanks to its Aqua Beat feature, even your dirtiest of clothes come out clean and fresh after a wash. Its customizable washing programs let you choose a washing course that best suits the fabric being put for a wash. To top it off, the washing machine also features a Magic Filter that, irrespective of the water level in the machine, traps dirt and lint from clothes while they are being washed.",
    price: 16790,
    rating: 3.5,
    company_name: "Panasonic",
    category: "Washing Machine",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/kjrh2fk0/washing-machine-new/n/g/h/7-na-f70lf1hrb-panasonic-original-imafz965ahvchzxz.jpeg?q=70",
      "https://youtu.be/x0aM41rMneY",
      "https://rukminim2.flixcart.com/image/416/416/kjrh2fk0/washing-machine-new/n/g/h/7-na-f70lf1hrb-panasonic-original-imafz96522hfeaxd.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 29,
    name: "Motorola 10.5 kg 5 Star Smart Wi-Fi Enabled Inverter Technology Fully Automatic Front Load with In-built Heater Grey  (105FLIWBM5DG)",
    desc: "Doing your laundry can be hectic. Boasting TruWifi Technology, this washing machine can be controlled from anywhere using your smartphone. Its TruSmart Sensors and Renesas Chipset ensure that the temperature, water level, foam level, weight, and speed are ideal to give your clothes a nice wash even when the voltage is fluctuating (up to 500 V).",
    price: 28990,
    rating: 3.5,
    company_name: "Motorola",
    category: "Washing Machine",
    img: [
      "https://rukminim1.flixcart.com/image/416/416/kgl5ua80/washing-machine-new/k/w/s/105fliwbm5dg-motorola-original-imafwse6knmbgy48.jpeg?q=70",
      "https://rukminim1.flixcart.com/image/416/416/kfzq8i80/washing-machine-new/k/w/s/105fliwbm5dg-motorola-original-imafwb6vxmhzy5hw.jpeg?q=70",
      "https://youtu.be/VGWYR9H33Eo",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 30,
    name: "BOSCH 7 kg Drive Motor, Anti Tangle, Anti Vibration Fully Automatic Front Load with In-built Heater Grey  (WAJ2416SIN)",
    desc: "Fully Automatic Front Load Washing Machines have Great Wash Quality with very less running cost 1200 RPM : Higher the spin speed, lower the drying time 5 Star Rating 7 kg",
    price: 31990,
    rating: 4.6,
    company_name: "BOSCH",
    category: "Washing Machine",
    img: [
      "https://rukminim2.flixcart.com/image/416/416/kkzrpu80/washing-machine-new/8/i/a/7-waj2416sin-bosch-original-imagy7rpzjhvvhdv.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/416/416/kwnv6a80/washing-machine-new/7/4/z/-original-imag9abgbusewazp.jpeg?q=70",
      "https://youtu.be/boE98Fq1We4",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 31,
    name: "LG 80 cm (32 inch) HD Ready LED Smart TV  (32LM565BPTA)",
    desc: "This LG Smart TV comes equipped with a host of impressive features to delight your senses. While its Dynamic Color Enhancer produces vivid and lifelike colors on the screen, the LG WebOS feature lets you watch shows and movies from your favourite streaming services, such as Netflix and Disney+Hotstar. Also, the DTX Virtual:X technology delivers multi-dimensional sound to ensure an immersive listening experience.",
    price: 17499,
    rating: 3,
    company_name: "LG",
    category: "TV",
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kdyus280/television/g/d/q/lg-32lm565bpta-32lm565bpta-original-imafurgkdrjfggbw.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kdyus280/television/g/d/q/lg-32lm565bpta-32lm565bpta-original-imafurgkf3ycgxbw.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kdyus280/television/g/d/q/lg-32lm565bpta-32lm565bpta-original-imafurgk3fsqyjwm.jpeg?q=70",
    ],

    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 32,
    name: "Vu Premium 108 cm (43 inch) Full HD LED Smart Android TV  (43UA)",
    desc: "Stay entertained and engrossed in your favourite content as you bring home this Vu Premium 43UA Television. The High Bright IPS panel of this TV helps to optimize brightness and enhance the visual quality thus, transforming your TV-viewing experience into an immersive one. Also, this TV comes with 30 W speakers and Dolby Audio so that you can indulge in excellent sound experience. Moreover, thanks to the in-built access to Netflix, Amazon, and Hotstar streaming platforms, you can enjoy accessing multiple content according to your convenience.",
    price: 21999,
    rating: 4.2,
    company_name: "Vu",
    category: "TV",
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kynb6vk0/television/r/5/g/-original-imagatzzmayhsjzc.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kxuqdu80/television/t/t/2/43ua-43ua-vu-original-imaga7snutyujtns.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/kxuqdu80/television/f/w/x/43ua-43ua-vu-original-imaga7snjzefh6cc.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 33,
    name: "Mi 5X 108 cm (43 inch) Ultra HD (4K) LED Smart Android TV with Dolby Atmos and Dolby Vision",
    desc: "The sleek and powerful Mi TV 5X is an ideal home entertainment option for your classy, modern humble abode. This appliance features a Premium Metal Bezel-less Design for a distraction-free visual experience, 30 W Powerful Speakers with Dolby Atmos for immersive sound, and Far-field Mics with Google Assistant to easily manage your entertainment using your voice.",
    price: 31999,
    rating: 4.5,
    company_name: "Mi",
    category: "TV",
    img: [
      "https://rukminim2.flixcart.com/image/832/832/ksoz53k0/television/c/p/h/l43m6-es-mi-original-imag6774wykv4ps8.jpeg?q=70",
      "https://youtu.be/LMSgBcgP13I",
    ],
    date: "23-03-2022",
    delivery: true,
  },

  {
    id: 34,
    name: "OnePlus U1S 139 cm (55 inch) Ultra HD (4K) LED Smart Android TV  (55UC1A00)",
    desc: " The OnePlus 50UC1A00 TV is your one home entertainment appliance for immersive, unlimited, and exciting audio-visual delight. This television features a 4K UHD Display for detailed, clear, and immersive visuals, Dynaudio sound offers well-balanced audio, and OnePlus Connect 2.0 to connect your smartphone to this TV.",
    price: 46999,
    rating: 4.9,
    company_name: "OnePlus",
    category: "TV",
    img: [
      "https://rukminim2.flixcart.com/image/832/832/kuwzssw0/television/d/f/q/u-series-55-u1s-55uc1a00-oneplus-original-imag7xtn86zveeb7.jpeg?q=70",
      "https://youtu.be/7MAEulKAAUU",
    ],
    date: "23-03-2022",
    delivery: true,
  },
  {
    id: 35,
    name: "Xiaomi 5A 100 cm (40 inch) Full HD LED Smart Android TV with Dolby Audio (2022 Model)",
    desc: "You can enjoy your favourite movies, catch up on news, and binge-watch TV series on the Xiaomi L40M7-EAIN FHD Smart TV. It features an elegant metal frame with a bezel-less design, allowing you to enjoy a widescreen view. In addition, this TV is sure to enhance your aural experience with Dolby Audio, which provides 24 W high-fidelity sound. Furthermore, boasting a full HD display and wide colour gamut, this TV provides high-quality visuals.",
    price: 22999,
    rating: 4.3,
    company_name: "Xiami",
    category: "TV",
    img: [
      "https://rukminim2.flixcart.com/image/832/832/l2ghgnk0/television/k/t/h/l40m7-eain-mi-original-imagdsdwkephupc5.jpeg?q=70",
      "https://rukminim2.flixcart.com/image/832/832/l2ghgnk0/television/i/q/g/l40m7-eain-mi-original-imagdsdwgbrtzyzz.jpeg?q=70",
    ],
    date: "23-03-2022",
    delivery: true,
  },
];
