import StoreProvider from "@/lib/StoreProvider";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import NavSpaceFiller from "@/components/NavSpaceFiller";

export const metadata = {
  title: "STOFFSPOT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <head>
          <link
            href="https://fonts.cdnfonts.com/css/abeatbykai"
            rel="stylesheet"
          />
          <style>
            @import url('https://fonts.cdnfonts.com/css/abeatbykai');
          </style>

          <link rel="icon" href="/logo.svg" sizes="any" />
        </head>
        <body>
          <Nav />
          <NavSpaceFiller />
          {children}
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
