import StoreProvider from "@/lib/StoreProvider";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import NavSpaceFiller from "@/components/NavSpaceFiller";

export const metadata = {
  title: "STOFFSPOT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html lang="en">
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
            rel="stylesheet"
          />
          <link rel="icon" href="/logo.svg" sizes="any" />
        </head>
        <body>
          <Nav />
          <NavSpaceFiller />
          {children}
          <Footer />
        </body>
      </html>
    </StoreProvider>
  );
}
